local _, addon = ...
local CONSTANTS = addon.CONSTANTS
--==========================================================
-- Configuration and related utility functions
--==========================================================
function BWQ:C(k)
	if BWQcfg.usePerCharacterSettings then
		return BWQcfgPerCharacter[k]
	else
		return BWQcfg[k]
	end
end

--==========================================================
-- Default Configuration
--==========================================================
BWQ.defaultConfig = {
	-- general
	attachToWorldMap = false,
	showOnClick = false,
	usePerCharacterSettings = false,
	enableClickToOpenMap = false,
	enableTomTomWaypointsOnClick = true,
	spewDebugInfo = false,
	alwaysShowBountyQuests = true,
	alwaysShowEpicQuests = true,
	onlyShowRareOrAbove = false,
	showTotalsInBrokerText = true,
		brokerShowAP = true,
		brokerShowServiceMedals = true,
		brokerShowWakeningEssences = true,
		brokerShowWarResources = true,
		brokerShowPrismaticManapearl = true,
		brokerShowCyphersOfTheFirstOnes = true,
		brokerGratefulOffering = true,
		brokerShowResources = true,
		brokerShowLegionfallSupplies = true,
		brokerShowXP = true,
		brokerShowHonor = true,
		brokerShowGold = false,
		brokerShowGear = false,
		brokerShowMarkOfHonor = false,
		brokerShowHerbalism = false,
		brokerShowMining = false,
		brokerShowFishing = false,
		brokerShowSkinning = false,
		brokerShowBloodOfSargeras = false,
		brokerShowDragonIslesSupplies = true,
		brokerShowElementalOverflow = true,
		brokerShowFlightstones = true,
		brokerShowWhelplingsDreamingCrest = true,
		brokerShowDrakesDreamingCrest = true,
		brokerShowWyrmsDreamingCrest = true,
		brokerShowAspectsDreamingCrest = true,
		brokerShowWhelplingsAwakenedCrest = true,
		brokerShowDrakesAwakenedCrest = true,
		brokerShowWyrmsAwakenedCrest = true,
		brokerShowAspectsAwakenedCrest = true,
		brokerShowMysteriousFragment = true,
		brokerShowResonanceCrystals = true,
		brokerShowTheAssemblyoftheDeeps = true,
		brokerShowValorstones = true,
		brokerShowKej = true,
		brokerShowCouncilofDornogal = true,
		brokerShowHallowfallArathi = true,
		brokerShowTheWeaver = true,
		brokerShowTheGeneral = true,
		brokerShowTheVizier = true,
		brokerShowBloodyTokens = true,
		brokerShowPolishedPetCharms = false,
	sortByTimeRemaining = false,
	-- reward type
	showDragonIslesSupplies = true,
	showElementalOverflow = true,
	showFlightstones = true,
	showWhelplingsDreamingCrest = true,
	showDrakesDreamingCrest = true,
	showWyrmsDreamingCrest = true,
	showAspectsDreamingCrest = true,
	showWhelplingsAwakenedCrest = true,
	showDrakesAwakenedCrest = true,
	showWyrmsAwakenedCrest = true,
	showAspectsAwakenedCrest = true,
	showMysteriousFragment = true,
	showResonanceCrystals = true,
	showCouncilofDornogal = true,
	showTheAssemblyoftheDeeps = true,
	showHallowfallArathi = true,
	showTheWeaver = true,
	showTheGeneral = true,
	showTheVizier = true,
	showValorstones = true,
	showKej = true,
	showBloodyTokens = true,
	showArtifactPower = true,
	showPrismaticManapearl = true,
	showCyphersOfTheFirstOnes = true,
	showGratefulOffering = true,
	showItems = true,
		showGear = true,
		showRelics = true,
		showCraftingMaterials = true,
		showConduits = true,
		showMarkOfHonor = true,
		showOtherItems = true,
	showTWWReputation = true,
	showDFReputation = true,
	showSLReputation = true,
	showBFAReputation = true,
	showBFAServiceMedals = true,
	showXP = true,
	showHonor = true,
	showLowGold = true,
	showHighGold = true,
	showWarResources = true,
	showAnima = true,
	showResources = true,
	showLegionfallSupplies = true,
	showNethershards = true,
	showArgunite = true,
	showWakeningEssences = true,
	-- quest type
	showProfession = true,
		showProfessionAlchemy = true,
		showProfessionBlacksmithing = true,
		showProfessionInscription = true,
		showProfessionJewelcrafting = true,
		showProfessionLeatherworking = true,
		showProfessionTailoring = true,
		showProfessionEnchanting = true,
		showProfessionEngineering = true,
		showProfessionHerbalism = true,
		showProfessionMining = true,
		showProfessionSkinning = true,
		showProfessionCooking = true,
		showProfessionArchaeology = true,
		showProfessionFishing = true,
	showDungeon = true,
	showDragonRiderRacing = true,
	showPvP = true,
	hideFactionColumn = false,
	hideFactionParagonBars = false,
		-- Dragonflight
		alwaysShowDragonscaleExpedition = false,
		alwaysShowIskaaraTuskarr = false,
		alwaysShowMaruukCentaur = false,
		alwaysShowValdrakkenAccord = false,
		alwaysShowLoammNiffen = false,
		alwaysShowDreamWardens = false,
		-- Shadowlands
		alwaysShowAscended = false,
		alwaysShowUndyingArmy = false,
		alwaysShowCourtofHarvesters = false,
		alwaysShowAvowed = false,
		alwaysShowWildHunt = false,
		alwaysShowDeathsAdvance = false,
		alwaysShowEnlightened = false,
		-- BFA
		alwaysShow7thLegion = false,
		alwaysShowStormsWake = false,
		alwaysShowOrderOfEmbers = false,
		alwaysShowProudmooreAdmiralty = false,
		alwaysShowWavebladeAnkoan = false,
		alwaysShowTheHonorbound = false,
		alwaysShowZandalariEmpire = false,
		alwaysShowTalanjisExpedition = false,
		alwaysShowVoldunai = false,
		alwaysShowTheUnshackled = false,
		alwaysShowRustboltResistance = false,
		alwaysShowTortollanSeekers = false,
		alwaysShowChampionsOfAzeroth = false,
		-- Legion
		alwaysShowCourtOfFarondis = false,
		alwaysShowDreamweavers = false,
		alwaysShowHighmountainTribe = false,
		alwaysShowNightfallen = false,
		alwaysShowWardens = false,
		alwaysShowValarjar = false,
		alwaysShowArmiesOfLegionfall = false,
		alwaysShowArmyOfTheLight = false,
		alwaysShowArgussianReach = false,
	showPetBattle = true,
	hidePetBattleBountyQuests = false,
	alwaysShowPetBattleFamilyFamiliar = true,

	collapsedZones = {},
}